# Generated by Django 3.1.2 on 2021-06-25 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.CharField(db_column='C_ID', max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('attributes', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('i_id', models.CharField(db_column='I_ID', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('office', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('r_id', models.AutoField(db_column='R_ID', primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
                ('comment', models.CharField(db_column='comment_', max_length=1000)),
                ('time', models.DateTimeField(auto_now=True, db_column='time_', null=True)),
                ('c_id', models.ForeignKey(blank=True, db_column='C_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.course')),
                ('username', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='i_id',
            field=models.ForeignKey(blank=True, db_column='I_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='forum.instructor'),
        ),
    ]
